#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using CODECorp.WcfIdentity.Models;

namespace CODECorp.WcfIdentity.Models
{
    public partial class AspNetUser
    {
        private string _id;
        [StringLength(128)]
        [Required()]
        [Key()]
        public virtual string Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        private string _userName;
        public virtual string UserName
        {
            get
            {
                return this._userName;
            }
            set
            {
                this._userName = value;
            }
        }

        private string _passwordHash;
        public virtual string PasswordHash
        {
            get
            {
                return this._passwordHash;
            }
            set
            {
                this._passwordHash = value;
            }
        }

        private string _securityStamp;
        public virtual string SecurityStamp
        {
            get
            {
                return this._securityStamp;
            }
            set
            {
                this._securityStamp = value;
            }
        }

        private string _discriminator;
        [StringLength(128)]
        [Required()]
        public virtual string Discriminator
        {
            get
            {
                return this._discriminator;
            }
            set
            {
                this._discriminator = value;
            }
        }

        private string _lastName;
        [StringLength(500)]
        public virtual string LastName
        {
            get
            {
                return this._lastName;
            }
            set
            {
                this._lastName = value;
            }
        }

        private string _firstName;
        [StringLength(500)]
        public virtual string FirstName
        {
            get
            {
                return this._firstName;
            }
            set
            {
                this._firstName = value;
            }
        }

        private IList<AspNetUserLogin> _aspNetUserLogins = new List<AspNetUserLogin>();
        public virtual IList<AspNetUserLogin> AspNetUserLogins
        {
            get
            {
                return this._aspNetUserLogins;
            }
        }

        private IList<AspNetUserClaim> _aspNetUserClaims = new List<AspNetUserClaim>();
        public virtual IList<AspNetUserClaim> AspNetUserClaims
        {
            get
            {
                return this._aspNetUserClaims;
            }
        }

        private IList<AspNetRole> _aspNetRoles = new List<AspNetRole>();
        public virtual IList<AspNetRole> AspNetRoles
        {
            get
            {
                return this._aspNetRoles;
            }
        }

    }
}
#pragma warning restore 1591
