#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel.DataAnnotations;
using CODECorp.WcfIdentity.Models;

namespace CODECorp.WcfIdentity.Models
{
    public partial class AspNetUserLogin
    {
        private string _userId;
        [StringLength(128)]
        [Required()]
        [Key()]
        public virtual string UserId
        {
            get
            {
                return this._userId;
            }
            set
            {
                this._userId = value;
            }
        }

        private string _loginProvider;
        [StringLength(128)]
        [Required()]
        [Key()]
        public virtual string LoginProvider
        {
            get
            {
                return this._loginProvider;
            }
            set
            {
                this._loginProvider = value;
            }
        }

        private string _providerKey;
        [StringLength(128)]
        [Required()]
        [Key()]
        public virtual string ProviderKey
        {
            get
            {
                return this._providerKey;
            }
            set
            {
                this._providerKey = value;
            }
        }

        private AspNetUser _aspNetUser;
        public virtual AspNetUser AspNetUser
        {
            get
            {
                return this._aspNetUser;
            }
            set
            {
                this._aspNetUser = value;
            }
        }

    }
}
#pragma warning restore 1591
