#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CODECorp.WcfIdentity.Models;

namespace CODECorp.WcfIdentity.Models
{
    public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
    {
        private static string connectionStringName = @"DefaultConnection";

        private static BackendConfiguration backend = GetBackendConfiguration();

        private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");

        public EntitiesModel()
            : base(connectionStringName, backend, metadataSource)
        { }

        public EntitiesModel(string connection)
            : base(connection, backend, metadataSource)
        { }

        public EntitiesModel(BackendConfiguration backendConfiguration)
            : base(connectionStringName, backendConfiguration, metadataSource)
        { }

        public EntitiesModel(string connection, MetadataSource metadataSource)
            : base(connection, backend, metadataSource)
        { }

        public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
            : base(connection, backendConfiguration, metadataSource)
        { }

        public IQueryable<AspNetUser> AspNetUsers
        {
            get
            {
                return this.GetAll<AspNetUser>();
            }
        }

        public IQueryable<AspNetUserLogin> AspNetUserLogins
        {
            get
            {
                return this.GetAll<AspNetUserLogin>();
            }
        }

        public IQueryable<AspNetUserClaim> AspNetUserClaims
        {
            get
            {
                return this.GetAll<AspNetUserClaim>();
            }
        }

        public IQueryable<AspNetRole> AspNetRoles
        {
            get
            {
                return this.GetAll<AspNetRole>();
            }
        }

        public static BackendConfiguration GetBackendConfiguration()
        {
            BackendConfiguration backend = new BackendConfiguration();
            backend.Backend = "MsSql";
            backend.ProviderName = "System.Data.SqlClient";
            return backend;
        }
    }

    public interface IEntitiesModelUnitOfWork : IUnitOfWork
    {
        IQueryable<AspNetUser> AspNetUsers
        {
            get;
        }
        IQueryable<AspNetUserLogin> AspNetUserLogins
        {
            get;
        }
        IQueryable<AspNetUserClaim> AspNetUserClaims
        {
            get;
        }
        IQueryable<AspNetRole> AspNetRoles
        {
            get;
        }
    }
}
#pragma warning restore 1591
